language: node_js

os:
  - linux

node_js:
  - "0.12"
  - "0.10"
  - "4.3"
  - "5.6"
  - "6.3.0"
  - "6.4"

sudo: required

dist: trusty

env:
 - TRAVIS_OS_UNAME=$(uname -s)

install:
 - if [[ $TRAVIS_OS_UNAME = 'Linux' ]]; then bash travis-linux-deps.sh; fi
 - if [[ $TRAVIS_OS_UNAME = 'Darwin' ]]; then bash travis-osx-deps.sh; fi

notifications:
  email:
    - vebruijn@gmail.com

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang
